/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const ProfileLazyImport = createFileRoute('/profile')()
const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()
const CarsIndexLazyImport = createFileRoute('/cars/')()
const AdminIndexLazyImport = createFileRoute('/admin/')()
const AdminTypeIndexLazyImport = createFileRoute('/admin/type/')()
const AdminTransmissionIndexLazyImport = createFileRoute(
  '/admin/transmission/',
)()
const AdminModelIndexLazyImport = createFileRoute('/admin/model/')()
const AdminManufactureIndexLazyImport = createFileRoute('/admin/manufacture/')()
const AdminCarspecsIndexLazyImport = createFileRoute('/admin/carspecs/')()
const AdminCarsIndexLazyImport = createFileRoute('/admin/cars/')()
const AdminCaroptionsIndexLazyImport = createFileRoute('/admin/caroptions/')()
const AdminTypeCreateLazyImport = createFileRoute('/admin/type/create')()
const AdminTypeIdLazyImport = createFileRoute('/admin/type/$id')()
const AdminTransmissionCreateLazyImport = createFileRoute(
  '/admin/transmission/create',
)()
const AdminTransmissionIdLazyImport = createFileRoute(
  '/admin/transmission/$id',
)()
const AdminModelCreateLazyImport = createFileRoute('/admin/model/create')()
const AdminModelIdLazyImport = createFileRoute('/admin/model/$id')()
const AdminManufactureCreateLazyImport = createFileRoute(
  '/admin/manufacture/create',
)()
const AdminManufactureIdLazyImport = createFileRoute('/admin/manufacture/$id')()
const AdminCarspecsCreateLazyImport = createFileRoute(
  '/admin/carspecs/create',
)()
const AdminCarspecsIdLazyImport = createFileRoute('/admin/carspecs/$id')()
const AdminCarsCreateLazyImport = createFileRoute('/admin/cars/create')()
const AdminCarsIdLazyImport = createFileRoute('/admin/cars/$id')()
const AdminCaroptionsCreateLazyImport = createFileRoute(
  '/admin/caroptions/create',
)()
const AdminCaroptionsIdLazyImport = createFileRoute('/admin/caroptions/$id')()
const AdminTypeEditIdLazyImport = createFileRoute('/admin/type/edit/$id')()
const AdminTransmissionEditIdLazyImport = createFileRoute(
  '/admin/transmission/edit/$id',
)()
const AdminModelEditIdLazyImport = createFileRoute('/admin/model/edit/$id')()
const AdminManufactureEditIdLazyImport = createFileRoute(
  '/admin/manufacture/edit/$id',
)()
const AdminCarspecsEditIdLazyImport = createFileRoute(
  '/admin/carspecs/edit/$id',
)()
const AdminCarsEditIdLazyImport = createFileRoute('/admin/cars/edit/$id')()
const AdminCaroptionsEditIdLazyImport = createFileRoute(
  '/admin/caroptions/edit/$id',
)()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const ProfileLazyRoute = ProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CarsIndexLazyRoute = CarsIndexLazyImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cars/index.lazy').then((d) => d.Route))

const AdminIndexLazyRoute = AdminIndexLazyImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))

const AdminTypeIndexLazyRoute = AdminTypeIndexLazyImport.update({
  id: '/admin/type/',
  path: '/admin/type/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/type/index.lazy').then((d) => d.Route),
)

const AdminTransmissionIndexLazyRoute = AdminTransmissionIndexLazyImport.update(
  {
    id: '/admin/transmission/',
    path: '/admin/transmission/',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/admin/transmission/index.lazy').then((d) => d.Route),
)

const AdminModelIndexLazyRoute = AdminModelIndexLazyImport.update({
  id: '/admin/model/',
  path: '/admin/model/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/model/index.lazy').then((d) => d.Route),
)

const AdminManufactureIndexLazyRoute = AdminManufactureIndexLazyImport.update({
  id: '/admin/manufacture/',
  path: '/admin/manufacture/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/manufacture/index.lazy').then((d) => d.Route),
)

const AdminCarspecsIndexLazyRoute = AdminCarspecsIndexLazyImport.update({
  id: '/admin/carspecs/',
  path: '/admin/carspecs/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/carspecs/index.lazy').then((d) => d.Route),
)

const AdminCarsIndexLazyRoute = AdminCarsIndexLazyImport.update({
  id: '/admin/cars/',
  path: '/admin/cars/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/cars/index.lazy').then((d) => d.Route),
)

const AdminCaroptionsIndexLazyRoute = AdminCaroptionsIndexLazyImport.update({
  id: '/admin/caroptions/',
  path: '/admin/caroptions/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/caroptions/index.lazy').then((d) => d.Route),
)

const AdminTypeCreateLazyRoute = AdminTypeCreateLazyImport.update({
  id: '/admin/type/create',
  path: '/admin/type/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/type/create.lazy').then((d) => d.Route),
)

const AdminTypeIdLazyRoute = AdminTypeIdLazyImport.update({
  id: '/admin/type/$id',
  path: '/admin/type/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/type/$id.lazy').then((d) => d.Route),
)

const AdminTransmissionCreateLazyRoute =
  AdminTransmissionCreateLazyImport.update({
    id: '/admin/transmission/create',
    path: '/admin/transmission/create',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/admin/transmission/create.lazy').then((d) => d.Route),
  )

const AdminTransmissionIdLazyRoute = AdminTransmissionIdLazyImport.update({
  id: '/admin/transmission/$id',
  path: '/admin/transmission/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/transmission/$id.lazy').then((d) => d.Route),
)

const AdminModelCreateLazyRoute = AdminModelCreateLazyImport.update({
  id: '/admin/model/create',
  path: '/admin/model/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/model/create.lazy').then((d) => d.Route),
)

const AdminModelIdLazyRoute = AdminModelIdLazyImport.update({
  id: '/admin/model/$id',
  path: '/admin/model/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/model/$id.lazy').then((d) => d.Route),
)

const AdminManufactureCreateLazyRoute = AdminManufactureCreateLazyImport.update(
  {
    id: '/admin/manufacture/create',
    path: '/admin/manufacture/create',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/admin/manufacture/create.lazy').then((d) => d.Route),
)

const AdminManufactureIdLazyRoute = AdminManufactureIdLazyImport.update({
  id: '/admin/manufacture/$id',
  path: '/admin/manufacture/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/manufacture/$id.lazy').then((d) => d.Route),
)

const AdminCarspecsCreateLazyRoute = AdminCarspecsCreateLazyImport.update({
  id: '/admin/carspecs/create',
  path: '/admin/carspecs/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/carspecs/create.lazy').then((d) => d.Route),
)

const AdminCarspecsIdLazyRoute = AdminCarspecsIdLazyImport.update({
  id: '/admin/carspecs/$id',
  path: '/admin/carspecs/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/carspecs/$id.lazy').then((d) => d.Route),
)

const AdminCarsCreateLazyRoute = AdminCarsCreateLazyImport.update({
  id: '/admin/cars/create',
  path: '/admin/cars/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/cars/create.lazy').then((d) => d.Route),
)

const AdminCarsIdLazyRoute = AdminCarsIdLazyImport.update({
  id: '/admin/cars/$id',
  path: '/admin/cars/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/cars/$id.lazy').then((d) => d.Route),
)

const AdminCaroptionsCreateLazyRoute = AdminCaroptionsCreateLazyImport.update({
  id: '/admin/caroptions/create',
  path: '/admin/caroptions/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/caroptions/create.lazy').then((d) => d.Route),
)

const AdminCaroptionsIdLazyRoute = AdminCaroptionsIdLazyImport.update({
  id: '/admin/caroptions/$id',
  path: '/admin/caroptions/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/caroptions/$id.lazy').then((d) => d.Route),
)

const AdminTypeEditIdLazyRoute = AdminTypeEditIdLazyImport.update({
  id: '/admin/type/edit/$id',
  path: '/admin/type/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/type/edit/$id.lazy').then((d) => d.Route),
)

const AdminTransmissionEditIdLazyRoute =
  AdminTransmissionEditIdLazyImport.update({
    id: '/admin/transmission/edit/$id',
    path: '/admin/transmission/edit/$id',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/admin/transmission/edit/$id.lazy').then((d) => d.Route),
  )

const AdminModelEditIdLazyRoute = AdminModelEditIdLazyImport.update({
  id: '/admin/model/edit/$id',
  path: '/admin/model/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/model/edit/$id.lazy').then((d) => d.Route),
)

const AdminManufactureEditIdLazyRoute = AdminManufactureEditIdLazyImport.update(
  {
    id: '/admin/manufacture/edit/$id',
    path: '/admin/manufacture/edit/$id',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/admin/manufacture/edit/$id.lazy').then((d) => d.Route),
)

const AdminCarspecsEditIdLazyRoute = AdminCarspecsEditIdLazyImport.update({
  id: '/admin/carspecs/edit/$id',
  path: '/admin/carspecs/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/carspecs/edit/$id.lazy').then((d) => d.Route),
)

const AdminCarsEditIdLazyRoute = AdminCarsEditIdLazyImport.update({
  id: '/admin/cars/edit/$id',
  path: '/admin/cars/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/cars/edit/$id.lazy').then((d) => d.Route),
)

const AdminCaroptionsEditIdLazyRoute = AdminCaroptionsEditIdLazyImport.update({
  id: '/admin/caroptions/edit/$id',
  path: '/admin/caroptions/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/caroptions/edit/$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/caroptions/$id': {
      id: '/admin/caroptions/$id'
      path: '/admin/caroptions/$id'
      fullPath: '/admin/caroptions/$id'
      preLoaderRoute: typeof AdminCaroptionsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/caroptions/create': {
      id: '/admin/caroptions/create'
      path: '/admin/caroptions/create'
      fullPath: '/admin/caroptions/create'
      preLoaderRoute: typeof AdminCaroptionsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/cars/$id': {
      id: '/admin/cars/$id'
      path: '/admin/cars/$id'
      fullPath: '/admin/cars/$id'
      preLoaderRoute: typeof AdminCarsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/cars/create': {
      id: '/admin/cars/create'
      path: '/admin/cars/create'
      fullPath: '/admin/cars/create'
      preLoaderRoute: typeof AdminCarsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/carspecs/$id': {
      id: '/admin/carspecs/$id'
      path: '/admin/carspecs/$id'
      fullPath: '/admin/carspecs/$id'
      preLoaderRoute: typeof AdminCarspecsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/carspecs/create': {
      id: '/admin/carspecs/create'
      path: '/admin/carspecs/create'
      fullPath: '/admin/carspecs/create'
      preLoaderRoute: typeof AdminCarspecsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/manufacture/$id': {
      id: '/admin/manufacture/$id'
      path: '/admin/manufacture/$id'
      fullPath: '/admin/manufacture/$id'
      preLoaderRoute: typeof AdminManufactureIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/manufacture/create': {
      id: '/admin/manufacture/create'
      path: '/admin/manufacture/create'
      fullPath: '/admin/manufacture/create'
      preLoaderRoute: typeof AdminManufactureCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/model/$id': {
      id: '/admin/model/$id'
      path: '/admin/model/$id'
      fullPath: '/admin/model/$id'
      preLoaderRoute: typeof AdminModelIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/model/create': {
      id: '/admin/model/create'
      path: '/admin/model/create'
      fullPath: '/admin/model/create'
      preLoaderRoute: typeof AdminModelCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/transmission/$id': {
      id: '/admin/transmission/$id'
      path: '/admin/transmission/$id'
      fullPath: '/admin/transmission/$id'
      preLoaderRoute: typeof AdminTransmissionIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/transmission/create': {
      id: '/admin/transmission/create'
      path: '/admin/transmission/create'
      fullPath: '/admin/transmission/create'
      preLoaderRoute: typeof AdminTransmissionCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/type/$id': {
      id: '/admin/type/$id'
      path: '/admin/type/$id'
      fullPath: '/admin/type/$id'
      preLoaderRoute: typeof AdminTypeIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/type/create': {
      id: '/admin/type/create'
      path: '/admin/type/create'
      fullPath: '/admin/type/create'
      preLoaderRoute: typeof AdminTypeCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/caroptions/': {
      id: '/admin/caroptions/'
      path: '/admin/caroptions'
      fullPath: '/admin/caroptions'
      preLoaderRoute: typeof AdminCaroptionsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/cars/': {
      id: '/admin/cars/'
      path: '/admin/cars'
      fullPath: '/admin/cars'
      preLoaderRoute: typeof AdminCarsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/carspecs/': {
      id: '/admin/carspecs/'
      path: '/admin/carspecs'
      fullPath: '/admin/carspecs'
      preLoaderRoute: typeof AdminCarspecsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/manufacture/': {
      id: '/admin/manufacture/'
      path: '/admin/manufacture'
      fullPath: '/admin/manufacture'
      preLoaderRoute: typeof AdminManufactureIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/model/': {
      id: '/admin/model/'
      path: '/admin/model'
      fullPath: '/admin/model'
      preLoaderRoute: typeof AdminModelIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/transmission/': {
      id: '/admin/transmission/'
      path: '/admin/transmission'
      fullPath: '/admin/transmission'
      preLoaderRoute: typeof AdminTransmissionIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/type/': {
      id: '/admin/type/'
      path: '/admin/type'
      fullPath: '/admin/type'
      preLoaderRoute: typeof AdminTypeIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/caroptions/edit/$id': {
      id: '/admin/caroptions/edit/$id'
      path: '/admin/caroptions/edit/$id'
      fullPath: '/admin/caroptions/edit/$id'
      preLoaderRoute: typeof AdminCaroptionsEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/cars/edit/$id': {
      id: '/admin/cars/edit/$id'
      path: '/admin/cars/edit/$id'
      fullPath: '/admin/cars/edit/$id'
      preLoaderRoute: typeof AdminCarsEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/carspecs/edit/$id': {
      id: '/admin/carspecs/edit/$id'
      path: '/admin/carspecs/edit/$id'
      fullPath: '/admin/carspecs/edit/$id'
      preLoaderRoute: typeof AdminCarspecsEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/manufacture/edit/$id': {
      id: '/admin/manufacture/edit/$id'
      path: '/admin/manufacture/edit/$id'
      fullPath: '/admin/manufacture/edit/$id'
      preLoaderRoute: typeof AdminManufactureEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/model/edit/$id': {
      id: '/admin/model/edit/$id'
      path: '/admin/model/edit/$id'
      fullPath: '/admin/model/edit/$id'
      preLoaderRoute: typeof AdminModelEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/transmission/edit/$id': {
      id: '/admin/transmission/edit/$id'
      path: '/admin/transmission/edit/$id'
      fullPath: '/admin/transmission/edit/$id'
      preLoaderRoute: typeof AdminTransmissionEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/type/edit/$id': {
      id: '/admin/type/edit/$id'
      path: '/admin/type/edit/$id'
      fullPath: '/admin/type/edit/$id'
      preLoaderRoute: typeof AdminTypeEditIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/admin': typeof AdminIndexLazyRoute
  '/cars': typeof CarsIndexLazyRoute
  '/admin/caroptions/$id': typeof AdminCaroptionsIdLazyRoute
  '/admin/caroptions/create': typeof AdminCaroptionsCreateLazyRoute
  '/admin/cars/$id': typeof AdminCarsIdLazyRoute
  '/admin/cars/create': typeof AdminCarsCreateLazyRoute
  '/admin/carspecs/$id': typeof AdminCarspecsIdLazyRoute
  '/admin/carspecs/create': typeof AdminCarspecsCreateLazyRoute
  '/admin/manufacture/$id': typeof AdminManufactureIdLazyRoute
  '/admin/manufacture/create': typeof AdminManufactureCreateLazyRoute
  '/admin/model/$id': typeof AdminModelIdLazyRoute
  '/admin/model/create': typeof AdminModelCreateLazyRoute
  '/admin/transmission/$id': typeof AdminTransmissionIdLazyRoute
  '/admin/transmission/create': typeof AdminTransmissionCreateLazyRoute
  '/admin/type/$id': typeof AdminTypeIdLazyRoute
  '/admin/type/create': typeof AdminTypeCreateLazyRoute
  '/admin/caroptions': typeof AdminCaroptionsIndexLazyRoute
  '/admin/cars': typeof AdminCarsIndexLazyRoute
  '/admin/carspecs': typeof AdminCarspecsIndexLazyRoute
  '/admin/manufacture': typeof AdminManufactureIndexLazyRoute
  '/admin/model': typeof AdminModelIndexLazyRoute
  '/admin/transmission': typeof AdminTransmissionIndexLazyRoute
  '/admin/type': typeof AdminTypeIndexLazyRoute
  '/admin/caroptions/edit/$id': typeof AdminCaroptionsEditIdLazyRoute
  '/admin/cars/edit/$id': typeof AdminCarsEditIdLazyRoute
  '/admin/carspecs/edit/$id': typeof AdminCarspecsEditIdLazyRoute
  '/admin/manufacture/edit/$id': typeof AdminManufactureEditIdLazyRoute
  '/admin/model/edit/$id': typeof AdminModelEditIdLazyRoute
  '/admin/transmission/edit/$id': typeof AdminTransmissionEditIdLazyRoute
  '/admin/type/edit/$id': typeof AdminTypeEditIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/admin': typeof AdminIndexLazyRoute
  '/cars': typeof CarsIndexLazyRoute
  '/admin/caroptions/$id': typeof AdminCaroptionsIdLazyRoute
  '/admin/caroptions/create': typeof AdminCaroptionsCreateLazyRoute
  '/admin/cars/$id': typeof AdminCarsIdLazyRoute
  '/admin/cars/create': typeof AdminCarsCreateLazyRoute
  '/admin/carspecs/$id': typeof AdminCarspecsIdLazyRoute
  '/admin/carspecs/create': typeof AdminCarspecsCreateLazyRoute
  '/admin/manufacture/$id': typeof AdminManufactureIdLazyRoute
  '/admin/manufacture/create': typeof AdminManufactureCreateLazyRoute
  '/admin/model/$id': typeof AdminModelIdLazyRoute
  '/admin/model/create': typeof AdminModelCreateLazyRoute
  '/admin/transmission/$id': typeof AdminTransmissionIdLazyRoute
  '/admin/transmission/create': typeof AdminTransmissionCreateLazyRoute
  '/admin/type/$id': typeof AdminTypeIdLazyRoute
  '/admin/type/create': typeof AdminTypeCreateLazyRoute
  '/admin/caroptions': typeof AdminCaroptionsIndexLazyRoute
  '/admin/cars': typeof AdminCarsIndexLazyRoute
  '/admin/carspecs': typeof AdminCarspecsIndexLazyRoute
  '/admin/manufacture': typeof AdminManufactureIndexLazyRoute
  '/admin/model': typeof AdminModelIndexLazyRoute
  '/admin/transmission': typeof AdminTransmissionIndexLazyRoute
  '/admin/type': typeof AdminTypeIndexLazyRoute
  '/admin/caroptions/edit/$id': typeof AdminCaroptionsEditIdLazyRoute
  '/admin/cars/edit/$id': typeof AdminCarsEditIdLazyRoute
  '/admin/carspecs/edit/$id': typeof AdminCarspecsEditIdLazyRoute
  '/admin/manufacture/edit/$id': typeof AdminManufactureEditIdLazyRoute
  '/admin/model/edit/$id': typeof AdminModelEditIdLazyRoute
  '/admin/transmission/edit/$id': typeof AdminTransmissionEditIdLazyRoute
  '/admin/type/edit/$id': typeof AdminTypeEditIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/cars/': typeof CarsIndexLazyRoute
  '/admin/caroptions/$id': typeof AdminCaroptionsIdLazyRoute
  '/admin/caroptions/create': typeof AdminCaroptionsCreateLazyRoute
  '/admin/cars/$id': typeof AdminCarsIdLazyRoute
  '/admin/cars/create': typeof AdminCarsCreateLazyRoute
  '/admin/carspecs/$id': typeof AdminCarspecsIdLazyRoute
  '/admin/carspecs/create': typeof AdminCarspecsCreateLazyRoute
  '/admin/manufacture/$id': typeof AdminManufactureIdLazyRoute
  '/admin/manufacture/create': typeof AdminManufactureCreateLazyRoute
  '/admin/model/$id': typeof AdminModelIdLazyRoute
  '/admin/model/create': typeof AdminModelCreateLazyRoute
  '/admin/transmission/$id': typeof AdminTransmissionIdLazyRoute
  '/admin/transmission/create': typeof AdminTransmissionCreateLazyRoute
  '/admin/type/$id': typeof AdminTypeIdLazyRoute
  '/admin/type/create': typeof AdminTypeCreateLazyRoute
  '/admin/caroptions/': typeof AdminCaroptionsIndexLazyRoute
  '/admin/cars/': typeof AdminCarsIndexLazyRoute
  '/admin/carspecs/': typeof AdminCarspecsIndexLazyRoute
  '/admin/manufacture/': typeof AdminManufactureIndexLazyRoute
  '/admin/model/': typeof AdminModelIndexLazyRoute
  '/admin/transmission/': typeof AdminTransmissionIndexLazyRoute
  '/admin/type/': typeof AdminTypeIndexLazyRoute
  '/admin/caroptions/edit/$id': typeof AdminCaroptionsEditIdLazyRoute
  '/admin/cars/edit/$id': typeof AdminCarsEditIdLazyRoute
  '/admin/carspecs/edit/$id': typeof AdminCarspecsEditIdLazyRoute
  '/admin/manufacture/edit/$id': typeof AdminManufactureEditIdLazyRoute
  '/admin/model/edit/$id': typeof AdminModelEditIdLazyRoute
  '/admin/transmission/edit/$id': typeof AdminTransmissionEditIdLazyRoute
  '/admin/type/edit/$id': typeof AdminTypeEditIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin'
    | '/cars'
    | '/admin/caroptions/$id'
    | '/admin/caroptions/create'
    | '/admin/cars/$id'
    | '/admin/cars/create'
    | '/admin/carspecs/$id'
    | '/admin/carspecs/create'
    | '/admin/manufacture/$id'
    | '/admin/manufacture/create'
    | '/admin/model/$id'
    | '/admin/model/create'
    | '/admin/transmission/$id'
    | '/admin/transmission/create'
    | '/admin/type/$id'
    | '/admin/type/create'
    | '/admin/caroptions'
    | '/admin/cars'
    | '/admin/carspecs'
    | '/admin/manufacture'
    | '/admin/model'
    | '/admin/transmission'
    | '/admin/type'
    | '/admin/caroptions/edit/$id'
    | '/admin/cars/edit/$id'
    | '/admin/carspecs/edit/$id'
    | '/admin/manufacture/edit/$id'
    | '/admin/model/edit/$id'
    | '/admin/transmission/edit/$id'
    | '/admin/type/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin'
    | '/cars'
    | '/admin/caroptions/$id'
    | '/admin/caroptions/create'
    | '/admin/cars/$id'
    | '/admin/cars/create'
    | '/admin/carspecs/$id'
    | '/admin/carspecs/create'
    | '/admin/manufacture/$id'
    | '/admin/manufacture/create'
    | '/admin/model/$id'
    | '/admin/model/create'
    | '/admin/transmission/$id'
    | '/admin/transmission/create'
    | '/admin/type/$id'
    | '/admin/type/create'
    | '/admin/caroptions'
    | '/admin/cars'
    | '/admin/carspecs'
    | '/admin/manufacture'
    | '/admin/model'
    | '/admin/transmission'
    | '/admin/type'
    | '/admin/caroptions/edit/$id'
    | '/admin/cars/edit/$id'
    | '/admin/carspecs/edit/$id'
    | '/admin/manufacture/edit/$id'
    | '/admin/model/edit/$id'
    | '/admin/transmission/edit/$id'
    | '/admin/type/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/'
    | '/cars/'
    | '/admin/caroptions/$id'
    | '/admin/caroptions/create'
    | '/admin/cars/$id'
    | '/admin/cars/create'
    | '/admin/carspecs/$id'
    | '/admin/carspecs/create'
    | '/admin/manufacture/$id'
    | '/admin/manufacture/create'
    | '/admin/model/$id'
    | '/admin/model/create'
    | '/admin/transmission/$id'
    | '/admin/transmission/create'
    | '/admin/type/$id'
    | '/admin/type/create'
    | '/admin/caroptions/'
    | '/admin/cars/'
    | '/admin/carspecs/'
    | '/admin/manufacture/'
    | '/admin/model/'
    | '/admin/transmission/'
    | '/admin/type/'
    | '/admin/caroptions/edit/$id'
    | '/admin/cars/edit/$id'
    | '/admin/carspecs/edit/$id'
    | '/admin/manufacture/edit/$id'
    | '/admin/model/edit/$id'
    | '/admin/transmission/edit/$id'
    | '/admin/type/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  AdminIndexLazyRoute: typeof AdminIndexLazyRoute
  CarsIndexLazyRoute: typeof CarsIndexLazyRoute
  AdminCaroptionsIdLazyRoute: typeof AdminCaroptionsIdLazyRoute
  AdminCaroptionsCreateLazyRoute: typeof AdminCaroptionsCreateLazyRoute
  AdminCarsIdLazyRoute: typeof AdminCarsIdLazyRoute
  AdminCarsCreateLazyRoute: typeof AdminCarsCreateLazyRoute
  AdminCarspecsIdLazyRoute: typeof AdminCarspecsIdLazyRoute
  AdminCarspecsCreateLazyRoute: typeof AdminCarspecsCreateLazyRoute
  AdminManufactureIdLazyRoute: typeof AdminManufactureIdLazyRoute
  AdminManufactureCreateLazyRoute: typeof AdminManufactureCreateLazyRoute
  AdminModelIdLazyRoute: typeof AdminModelIdLazyRoute
  AdminModelCreateLazyRoute: typeof AdminModelCreateLazyRoute
  AdminTransmissionIdLazyRoute: typeof AdminTransmissionIdLazyRoute
  AdminTransmissionCreateLazyRoute: typeof AdminTransmissionCreateLazyRoute
  AdminTypeIdLazyRoute: typeof AdminTypeIdLazyRoute
  AdminTypeCreateLazyRoute: typeof AdminTypeCreateLazyRoute
  AdminCaroptionsIndexLazyRoute: typeof AdminCaroptionsIndexLazyRoute
  AdminCarsIndexLazyRoute: typeof AdminCarsIndexLazyRoute
  AdminCarspecsIndexLazyRoute: typeof AdminCarspecsIndexLazyRoute
  AdminManufactureIndexLazyRoute: typeof AdminManufactureIndexLazyRoute
  AdminModelIndexLazyRoute: typeof AdminModelIndexLazyRoute
  AdminTransmissionIndexLazyRoute: typeof AdminTransmissionIndexLazyRoute
  AdminTypeIndexLazyRoute: typeof AdminTypeIndexLazyRoute
  AdminCaroptionsEditIdLazyRoute: typeof AdminCaroptionsEditIdLazyRoute
  AdminCarsEditIdLazyRoute: typeof AdminCarsEditIdLazyRoute
  AdminCarspecsEditIdLazyRoute: typeof AdminCarspecsEditIdLazyRoute
  AdminManufactureEditIdLazyRoute: typeof AdminManufactureEditIdLazyRoute
  AdminModelEditIdLazyRoute: typeof AdminModelEditIdLazyRoute
  AdminTransmissionEditIdLazyRoute: typeof AdminTransmissionEditIdLazyRoute
  AdminTypeEditIdLazyRoute: typeof AdminTypeEditIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  AdminIndexLazyRoute: AdminIndexLazyRoute,
  CarsIndexLazyRoute: CarsIndexLazyRoute,
  AdminCaroptionsIdLazyRoute: AdminCaroptionsIdLazyRoute,
  AdminCaroptionsCreateLazyRoute: AdminCaroptionsCreateLazyRoute,
  AdminCarsIdLazyRoute: AdminCarsIdLazyRoute,
  AdminCarsCreateLazyRoute: AdminCarsCreateLazyRoute,
  AdminCarspecsIdLazyRoute: AdminCarspecsIdLazyRoute,
  AdminCarspecsCreateLazyRoute: AdminCarspecsCreateLazyRoute,
  AdminManufactureIdLazyRoute: AdminManufactureIdLazyRoute,
  AdminManufactureCreateLazyRoute: AdminManufactureCreateLazyRoute,
  AdminModelIdLazyRoute: AdminModelIdLazyRoute,
  AdminModelCreateLazyRoute: AdminModelCreateLazyRoute,
  AdminTransmissionIdLazyRoute: AdminTransmissionIdLazyRoute,
  AdminTransmissionCreateLazyRoute: AdminTransmissionCreateLazyRoute,
  AdminTypeIdLazyRoute: AdminTypeIdLazyRoute,
  AdminTypeCreateLazyRoute: AdminTypeCreateLazyRoute,
  AdminCaroptionsIndexLazyRoute: AdminCaroptionsIndexLazyRoute,
  AdminCarsIndexLazyRoute: AdminCarsIndexLazyRoute,
  AdminCarspecsIndexLazyRoute: AdminCarspecsIndexLazyRoute,
  AdminManufactureIndexLazyRoute: AdminManufactureIndexLazyRoute,
  AdminModelIndexLazyRoute: AdminModelIndexLazyRoute,
  AdminTransmissionIndexLazyRoute: AdminTransmissionIndexLazyRoute,
  AdminTypeIndexLazyRoute: AdminTypeIndexLazyRoute,
  AdminCaroptionsEditIdLazyRoute: AdminCaroptionsEditIdLazyRoute,
  AdminCarsEditIdLazyRoute: AdminCarsEditIdLazyRoute,
  AdminCarspecsEditIdLazyRoute: AdminCarspecsEditIdLazyRoute,
  AdminManufactureEditIdLazyRoute: AdminManufactureEditIdLazyRoute,
  AdminModelEditIdLazyRoute: AdminModelEditIdLazyRoute,
  AdminTransmissionEditIdLazyRoute: AdminTransmissionEditIdLazyRoute,
  AdminTypeEditIdLazyRoute: AdminTypeEditIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/login",
        "/profile",
        "/register",
        "/admin/",
        "/cars/",
        "/admin/caroptions/$id",
        "/admin/caroptions/create",
        "/admin/cars/$id",
        "/admin/cars/create",
        "/admin/carspecs/$id",
        "/admin/carspecs/create",
        "/admin/manufacture/$id",
        "/admin/manufacture/create",
        "/admin/model/$id",
        "/admin/model/create",
        "/admin/transmission/$id",
        "/admin/transmission/create",
        "/admin/type/$id",
        "/admin/type/create",
        "/admin/caroptions/",
        "/admin/cars/",
        "/admin/carspecs/",
        "/admin/manufacture/",
        "/admin/model/",
        "/admin/transmission/",
        "/admin/type/",
        "/admin/caroptions/edit/$id",
        "/admin/cars/edit/$id",
        "/admin/carspecs/edit/$id",
        "/admin/manufacture/edit/$id",
        "/admin/model/edit/$id",
        "/admin/transmission/edit/$id",
        "/admin/type/edit/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/login": {
      "filePath": "login.lazy.jsx"
    },
    "/profile": {
      "filePath": "profile.lazy.jsx"
    },
    "/register": {
      "filePath": "register.lazy.jsx"
    },
    "/admin/": {
      "filePath": "admin/index.lazy.jsx"
    },
    "/cars/": {
      "filePath": "cars/index.lazy.jsx"
    },
    "/admin/caroptions/$id": {
      "filePath": "admin/caroptions/$id.lazy.jsx"
    },
    "/admin/caroptions/create": {
      "filePath": "admin/caroptions/create.lazy.jsx"
    },
    "/admin/cars/$id": {
      "filePath": "admin/cars/$id.lazy.jsx"
    },
    "/admin/cars/create": {
      "filePath": "admin/cars/create.lazy.jsx"
    },
    "/admin/carspecs/$id": {
      "filePath": "admin/carspecs/$id.lazy.jsx"
    },
    "/admin/carspecs/create": {
      "filePath": "admin/carspecs/create.lazy.jsx"
    },
    "/admin/manufacture/$id": {
      "filePath": "admin/manufacture/$id.lazy.jsx"
    },
    "/admin/manufacture/create": {
      "filePath": "admin/manufacture/create.lazy.jsx"
    },
    "/admin/model/$id": {
      "filePath": "admin/model/$id.lazy.jsx"
    },
    "/admin/model/create": {
      "filePath": "admin/model/create.lazy.jsx"
    },
    "/admin/transmission/$id": {
      "filePath": "admin/transmission/$id.lazy.jsx"
    },
    "/admin/transmission/create": {
      "filePath": "admin/transmission/create.lazy.jsx"
    },
    "/admin/type/$id": {
      "filePath": "admin/type/$id.lazy.jsx"
    },
    "/admin/type/create": {
      "filePath": "admin/type/create.lazy.jsx"
    },
    "/admin/caroptions/": {
      "filePath": "admin/caroptions/index.lazy.jsx"
    },
    "/admin/cars/": {
      "filePath": "admin/cars/index.lazy.jsx"
    },
    "/admin/carspecs/": {
      "filePath": "admin/carspecs/index.lazy.jsx"
    },
    "/admin/manufacture/": {
      "filePath": "admin/manufacture/index.lazy.jsx"
    },
    "/admin/model/": {
      "filePath": "admin/model/index.lazy.jsx"
    },
    "/admin/transmission/": {
      "filePath": "admin/transmission/index.lazy.jsx"
    },
    "/admin/type/": {
      "filePath": "admin/type/index.lazy.jsx"
    },
    "/admin/caroptions/edit/$id": {
      "filePath": "admin/caroptions/edit/$id.lazy.jsx"
    },
    "/admin/cars/edit/$id": {
      "filePath": "admin/cars/edit/$id.lazy.jsx"
    },
    "/admin/carspecs/edit/$id": {
      "filePath": "admin/carspecs/edit/$id.lazy.jsx"
    },
    "/admin/manufacture/edit/$id": {
      "filePath": "admin/manufacture/edit/$id.lazy.jsx"
    },
    "/admin/model/edit/$id": {
      "filePath": "admin/model/edit/$id.lazy.jsx"
    },
    "/admin/transmission/edit/$id": {
      "filePath": "admin/transmission/edit/$id.lazy.jsx"
    },
    "/admin/type/edit/$id": {
      "filePath": "admin/type/edit/$id.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
