/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const ProfileLazyImport = createFileRoute('/profile')()
const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()
const TypeIndexLazyImport = createFileRoute('/type/')()
const TransmissionIndexLazyImport = createFileRoute('/transmission/')()
const ModelIndexLazyImport = createFileRoute('/model/')()
const ManufactureIndexLazyImport = createFileRoute('/manufacture/')()
const CarspecsIndexLazyImport = createFileRoute('/carspecs/')()
const CarsIndexLazyImport = createFileRoute('/cars/')()
const CaroptionsIndexLazyImport = createFileRoute('/caroptions/')()
const TypeCreateLazyImport = createFileRoute('/type/create')()
const TypeIdLazyImport = createFileRoute('/type/$id')()
const TransmissionCreateLazyImport = createFileRoute('/transmission/create')()
const TransmissionIdLazyImport = createFileRoute('/transmission/$id')()
const ModelCreateLazyImport = createFileRoute('/model/create')()
const ModelIdLazyImport = createFileRoute('/model/$id')()
const ManufactureCreateLazyImport = createFileRoute('/manufacture/create')()
const ManufactureIdLazyImport = createFileRoute('/manufacture/$id')()
const CarspecsCreateLazyImport = createFileRoute('/carspecs/create')()
const CarspecsIdLazyImport = createFileRoute('/carspecs/$id')()
const CarsCreateLazyImport = createFileRoute('/cars/create')()
const CarsIdLazyImport = createFileRoute('/cars/$id')()
const CaroptionsCreateLazyImport = createFileRoute('/caroptions/create')()
const CaroptionsIdLazyImport = createFileRoute('/caroptions/$id')()
const TypeEditIdLazyImport = createFileRoute('/type/edit/$id')()
const TransmissionEditIdLazyImport = createFileRoute('/transmission/edit/$id')()
const ModelEditIdLazyImport = createFileRoute('/model/edit/$id')()
const ManufactureEditIdLazyImport = createFileRoute('/manufacture/edit/$id')()
const CarspecsEditIdLazyImport = createFileRoute('/carspecs/edit/$id')()
const CarsEditIdLazyImport = createFileRoute('/cars/edit/$id')()
const CaroptionsEditIdLazyImport = createFileRoute('/caroptions/edit/$id')()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const ProfileLazyRoute = ProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TypeIndexLazyRoute = TypeIndexLazyImport.update({
  id: '/type/',
  path: '/type/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/type/index.lazy').then((d) => d.Route))

const TransmissionIndexLazyRoute = TransmissionIndexLazyImport.update({
  id: '/transmission/',
  path: '/transmission/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/transmission/index.lazy').then((d) => d.Route),
)

const ModelIndexLazyRoute = ModelIndexLazyImport.update({
  id: '/model/',
  path: '/model/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/model/index.lazy').then((d) => d.Route))

const ManufactureIndexLazyRoute = ManufactureIndexLazyImport.update({
  id: '/manufacture/',
  path: '/manufacture/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/manufacture/index.lazy').then((d) => d.Route),
)

const CarspecsIndexLazyRoute = CarspecsIndexLazyImport.update({
  id: '/carspecs/',
  path: '/carspecs/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/carspecs/index.lazy').then((d) => d.Route),
)

const CarsIndexLazyRoute = CarsIndexLazyImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cars/index.lazy').then((d) => d.Route))

const CaroptionsIndexLazyRoute = CaroptionsIndexLazyImport.update({
  id: '/caroptions/',
  path: '/caroptions/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/caroptions/index.lazy').then((d) => d.Route),
)

const TypeCreateLazyRoute = TypeCreateLazyImport.update({
  id: '/type/create',
  path: '/type/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/type/create.lazy').then((d) => d.Route))

const TypeIdLazyRoute = TypeIdLazyImport.update({
  id: '/type/$id',
  path: '/type/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/type/$id.lazy').then((d) => d.Route))

const TransmissionCreateLazyRoute = TransmissionCreateLazyImport.update({
  id: '/transmission/create',
  path: '/transmission/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/transmission/create.lazy').then((d) => d.Route),
)

const TransmissionIdLazyRoute = TransmissionIdLazyImport.update({
  id: '/transmission/$id',
  path: '/transmission/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/transmission/$id.lazy').then((d) => d.Route),
)

const ModelCreateLazyRoute = ModelCreateLazyImport.update({
  id: '/model/create',
  path: '/model/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/model/create.lazy').then((d) => d.Route))

const ModelIdLazyRoute = ModelIdLazyImport.update({
  id: '/model/$id',
  path: '/model/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/model/$id.lazy').then((d) => d.Route))

const ManufactureCreateLazyRoute = ManufactureCreateLazyImport.update({
  id: '/manufacture/create',
  path: '/manufacture/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/manufacture/create.lazy').then((d) => d.Route),
)

const ManufactureIdLazyRoute = ManufactureIdLazyImport.update({
  id: '/manufacture/$id',
  path: '/manufacture/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/manufacture/$id.lazy').then((d) => d.Route),
)

const CarspecsCreateLazyRoute = CarspecsCreateLazyImport.update({
  id: '/carspecs/create',
  path: '/carspecs/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/carspecs/create.lazy').then((d) => d.Route),
)

const CarspecsIdLazyRoute = CarspecsIdLazyImport.update({
  id: '/carspecs/$id',
  path: '/carspecs/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/carspecs/$id.lazy').then((d) => d.Route))

const CarsCreateLazyRoute = CarsCreateLazyImport.update({
  id: '/cars/create',
  path: '/cars/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cars/create.lazy').then((d) => d.Route))

const CarsIdLazyRoute = CarsIdLazyImport.update({
  id: '/cars/$id',
  path: '/cars/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cars/$id.lazy').then((d) => d.Route))

const CaroptionsCreateLazyRoute = CaroptionsCreateLazyImport.update({
  id: '/caroptions/create',
  path: '/caroptions/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/caroptions/create.lazy').then((d) => d.Route),
)

const CaroptionsIdLazyRoute = CaroptionsIdLazyImport.update({
  id: '/caroptions/$id',
  path: '/caroptions/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/caroptions/$id.lazy').then((d) => d.Route),
)

const TypeEditIdLazyRoute = TypeEditIdLazyImport.update({
  id: '/type/edit/$id',
  path: '/type/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/type/edit/$id.lazy').then((d) => d.Route))

const TransmissionEditIdLazyRoute = TransmissionEditIdLazyImport.update({
  id: '/transmission/edit/$id',
  path: '/transmission/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/transmission/edit/$id.lazy').then((d) => d.Route),
)

const ModelEditIdLazyRoute = ModelEditIdLazyImport.update({
  id: '/model/edit/$id',
  path: '/model/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/model/edit/$id.lazy').then((d) => d.Route),
)

const ManufactureEditIdLazyRoute = ManufactureEditIdLazyImport.update({
  id: '/manufacture/edit/$id',
  path: '/manufacture/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/manufacture/edit/$id.lazy').then((d) => d.Route),
)

const CarspecsEditIdLazyRoute = CarspecsEditIdLazyImport.update({
  id: '/carspecs/edit/$id',
  path: '/carspecs/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/carspecs/edit/$id.lazy').then((d) => d.Route),
)

const CarsEditIdLazyRoute = CarsEditIdLazyImport.update({
  id: '/cars/edit/$id',
  path: '/cars/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cars/edit/$id.lazy').then((d) => d.Route))

const CaroptionsEditIdLazyRoute = CaroptionsEditIdLazyImport.update({
  id: '/caroptions/edit/$id',
  path: '/caroptions/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/caroptions/edit/$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/caroptions/$id': {
      id: '/caroptions/$id'
      path: '/caroptions/$id'
      fullPath: '/caroptions/$id'
      preLoaderRoute: typeof CaroptionsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/caroptions/create': {
      id: '/caroptions/create'
      path: '/caroptions/create'
      fullPath: '/caroptions/create'
      preLoaderRoute: typeof CaroptionsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/cars/$id': {
      id: '/cars/$id'
      path: '/cars/$id'
      fullPath: '/cars/$id'
      preLoaderRoute: typeof CarsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/cars/create': {
      id: '/cars/create'
      path: '/cars/create'
      fullPath: '/cars/create'
      preLoaderRoute: typeof CarsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/carspecs/$id': {
      id: '/carspecs/$id'
      path: '/carspecs/$id'
      fullPath: '/carspecs/$id'
      preLoaderRoute: typeof CarspecsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/carspecs/create': {
      id: '/carspecs/create'
      path: '/carspecs/create'
      fullPath: '/carspecs/create'
      preLoaderRoute: typeof CarspecsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/manufacture/$id': {
      id: '/manufacture/$id'
      path: '/manufacture/$id'
      fullPath: '/manufacture/$id'
      preLoaderRoute: typeof ManufactureIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/manufacture/create': {
      id: '/manufacture/create'
      path: '/manufacture/create'
      fullPath: '/manufacture/create'
      preLoaderRoute: typeof ManufactureCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/model/$id': {
      id: '/model/$id'
      path: '/model/$id'
      fullPath: '/model/$id'
      preLoaderRoute: typeof ModelIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/model/create': {
      id: '/model/create'
      path: '/model/create'
      fullPath: '/model/create'
      preLoaderRoute: typeof ModelCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/transmission/$id': {
      id: '/transmission/$id'
      path: '/transmission/$id'
      fullPath: '/transmission/$id'
      preLoaderRoute: typeof TransmissionIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/transmission/create': {
      id: '/transmission/create'
      path: '/transmission/create'
      fullPath: '/transmission/create'
      preLoaderRoute: typeof TransmissionCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/type/$id': {
      id: '/type/$id'
      path: '/type/$id'
      fullPath: '/type/$id'
      preLoaderRoute: typeof TypeIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/type/create': {
      id: '/type/create'
      path: '/type/create'
      fullPath: '/type/create'
      preLoaderRoute: typeof TypeCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/caroptions/': {
      id: '/caroptions/'
      path: '/caroptions'
      fullPath: '/caroptions'
      preLoaderRoute: typeof CaroptionsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/carspecs/': {
      id: '/carspecs/'
      path: '/carspecs'
      fullPath: '/carspecs'
      preLoaderRoute: typeof CarspecsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/manufacture/': {
      id: '/manufacture/'
      path: '/manufacture'
      fullPath: '/manufacture'
      preLoaderRoute: typeof ManufactureIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/model/': {
      id: '/model/'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/transmission/': {
      id: '/transmission/'
      path: '/transmission'
      fullPath: '/transmission'
      preLoaderRoute: typeof TransmissionIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/type/': {
      id: '/type/'
      path: '/type'
      fullPath: '/type'
      preLoaderRoute: typeof TypeIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/caroptions/edit/$id': {
      id: '/caroptions/edit/$id'
      path: '/caroptions/edit/$id'
      fullPath: '/caroptions/edit/$id'
      preLoaderRoute: typeof CaroptionsEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/cars/edit/$id': {
      id: '/cars/edit/$id'
      path: '/cars/edit/$id'
      fullPath: '/cars/edit/$id'
      preLoaderRoute: typeof CarsEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/carspecs/edit/$id': {
      id: '/carspecs/edit/$id'
      path: '/carspecs/edit/$id'
      fullPath: '/carspecs/edit/$id'
      preLoaderRoute: typeof CarspecsEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/manufacture/edit/$id': {
      id: '/manufacture/edit/$id'
      path: '/manufacture/edit/$id'
      fullPath: '/manufacture/edit/$id'
      preLoaderRoute: typeof ManufactureEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/model/edit/$id': {
      id: '/model/edit/$id'
      path: '/model/edit/$id'
      fullPath: '/model/edit/$id'
      preLoaderRoute: typeof ModelEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/transmission/edit/$id': {
      id: '/transmission/edit/$id'
      path: '/transmission/edit/$id'
      fullPath: '/transmission/edit/$id'
      preLoaderRoute: typeof TransmissionEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/type/edit/$id': {
      id: '/type/edit/$id'
      path: '/type/edit/$id'
      fullPath: '/type/edit/$id'
      preLoaderRoute: typeof TypeEditIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/caroptions/$id': typeof CaroptionsIdLazyRoute
  '/caroptions/create': typeof CaroptionsCreateLazyRoute
  '/cars/$id': typeof CarsIdLazyRoute
  '/cars/create': typeof CarsCreateLazyRoute
  '/carspecs/$id': typeof CarspecsIdLazyRoute
  '/carspecs/create': typeof CarspecsCreateLazyRoute
  '/manufacture/$id': typeof ManufactureIdLazyRoute
  '/manufacture/create': typeof ManufactureCreateLazyRoute
  '/model/$id': typeof ModelIdLazyRoute
  '/model/create': typeof ModelCreateLazyRoute
  '/transmission/$id': typeof TransmissionIdLazyRoute
  '/transmission/create': typeof TransmissionCreateLazyRoute
  '/type/$id': typeof TypeIdLazyRoute
  '/type/create': typeof TypeCreateLazyRoute
  '/caroptions': typeof CaroptionsIndexLazyRoute
  '/cars': typeof CarsIndexLazyRoute
  '/carspecs': typeof CarspecsIndexLazyRoute
  '/manufacture': typeof ManufactureIndexLazyRoute
  '/model': typeof ModelIndexLazyRoute
  '/transmission': typeof TransmissionIndexLazyRoute
  '/type': typeof TypeIndexLazyRoute
  '/caroptions/edit/$id': typeof CaroptionsEditIdLazyRoute
  '/cars/edit/$id': typeof CarsEditIdLazyRoute
  '/carspecs/edit/$id': typeof CarspecsEditIdLazyRoute
  '/manufacture/edit/$id': typeof ManufactureEditIdLazyRoute
  '/model/edit/$id': typeof ModelEditIdLazyRoute
  '/transmission/edit/$id': typeof TransmissionEditIdLazyRoute
  '/type/edit/$id': typeof TypeEditIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/caroptions/$id': typeof CaroptionsIdLazyRoute
  '/caroptions/create': typeof CaroptionsCreateLazyRoute
  '/cars/$id': typeof CarsIdLazyRoute
  '/cars/create': typeof CarsCreateLazyRoute
  '/carspecs/$id': typeof CarspecsIdLazyRoute
  '/carspecs/create': typeof CarspecsCreateLazyRoute
  '/manufacture/$id': typeof ManufactureIdLazyRoute
  '/manufacture/create': typeof ManufactureCreateLazyRoute
  '/model/$id': typeof ModelIdLazyRoute
  '/model/create': typeof ModelCreateLazyRoute
  '/transmission/$id': typeof TransmissionIdLazyRoute
  '/transmission/create': typeof TransmissionCreateLazyRoute
  '/type/$id': typeof TypeIdLazyRoute
  '/type/create': typeof TypeCreateLazyRoute
  '/caroptions': typeof CaroptionsIndexLazyRoute
  '/cars': typeof CarsIndexLazyRoute
  '/carspecs': typeof CarspecsIndexLazyRoute
  '/manufacture': typeof ManufactureIndexLazyRoute
  '/model': typeof ModelIndexLazyRoute
  '/transmission': typeof TransmissionIndexLazyRoute
  '/type': typeof TypeIndexLazyRoute
  '/caroptions/edit/$id': typeof CaroptionsEditIdLazyRoute
  '/cars/edit/$id': typeof CarsEditIdLazyRoute
  '/carspecs/edit/$id': typeof CarspecsEditIdLazyRoute
  '/manufacture/edit/$id': typeof ManufactureEditIdLazyRoute
  '/model/edit/$id': typeof ModelEditIdLazyRoute
  '/transmission/edit/$id': typeof TransmissionEditIdLazyRoute
  '/type/edit/$id': typeof TypeEditIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/caroptions/$id': typeof CaroptionsIdLazyRoute
  '/caroptions/create': typeof CaroptionsCreateLazyRoute
  '/cars/$id': typeof CarsIdLazyRoute
  '/cars/create': typeof CarsCreateLazyRoute
  '/carspecs/$id': typeof CarspecsIdLazyRoute
  '/carspecs/create': typeof CarspecsCreateLazyRoute
  '/manufacture/$id': typeof ManufactureIdLazyRoute
  '/manufacture/create': typeof ManufactureCreateLazyRoute
  '/model/$id': typeof ModelIdLazyRoute
  '/model/create': typeof ModelCreateLazyRoute
  '/transmission/$id': typeof TransmissionIdLazyRoute
  '/transmission/create': typeof TransmissionCreateLazyRoute
  '/type/$id': typeof TypeIdLazyRoute
  '/type/create': typeof TypeCreateLazyRoute
  '/caroptions/': typeof CaroptionsIndexLazyRoute
  '/cars/': typeof CarsIndexLazyRoute
  '/carspecs/': typeof CarspecsIndexLazyRoute
  '/manufacture/': typeof ManufactureIndexLazyRoute
  '/model/': typeof ModelIndexLazyRoute
  '/transmission/': typeof TransmissionIndexLazyRoute
  '/type/': typeof TypeIndexLazyRoute
  '/caroptions/edit/$id': typeof CaroptionsEditIdLazyRoute
  '/cars/edit/$id': typeof CarsEditIdLazyRoute
  '/carspecs/edit/$id': typeof CarspecsEditIdLazyRoute
  '/manufacture/edit/$id': typeof ManufactureEditIdLazyRoute
  '/model/edit/$id': typeof ModelEditIdLazyRoute
  '/transmission/edit/$id': typeof TransmissionEditIdLazyRoute
  '/type/edit/$id': typeof TypeEditIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/caroptions/$id'
    | '/caroptions/create'
    | '/cars/$id'
    | '/cars/create'
    | '/carspecs/$id'
    | '/carspecs/create'
    | '/manufacture/$id'
    | '/manufacture/create'
    | '/model/$id'
    | '/model/create'
    | '/transmission/$id'
    | '/transmission/create'
    | '/type/$id'
    | '/type/create'
    | '/caroptions'
    | '/cars'
    | '/carspecs'
    | '/manufacture'
    | '/model'
    | '/transmission'
    | '/type'
    | '/caroptions/edit/$id'
    | '/cars/edit/$id'
    | '/carspecs/edit/$id'
    | '/manufacture/edit/$id'
    | '/model/edit/$id'
    | '/transmission/edit/$id'
    | '/type/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/caroptions/$id'
    | '/caroptions/create'
    | '/cars/$id'
    | '/cars/create'
    | '/carspecs/$id'
    | '/carspecs/create'
    | '/manufacture/$id'
    | '/manufacture/create'
    | '/model/$id'
    | '/model/create'
    | '/transmission/$id'
    | '/transmission/create'
    | '/type/$id'
    | '/type/create'
    | '/caroptions'
    | '/cars'
    | '/carspecs'
    | '/manufacture'
    | '/model'
    | '/transmission'
    | '/type'
    | '/caroptions/edit/$id'
    | '/cars/edit/$id'
    | '/carspecs/edit/$id'
    | '/manufacture/edit/$id'
    | '/model/edit/$id'
    | '/transmission/edit/$id'
    | '/type/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/caroptions/$id'
    | '/caroptions/create'
    | '/cars/$id'
    | '/cars/create'
    | '/carspecs/$id'
    | '/carspecs/create'
    | '/manufacture/$id'
    | '/manufacture/create'
    | '/model/$id'
    | '/model/create'
    | '/transmission/$id'
    | '/transmission/create'
    | '/type/$id'
    | '/type/create'
    | '/caroptions/'
    | '/cars/'
    | '/carspecs/'
    | '/manufacture/'
    | '/model/'
    | '/transmission/'
    | '/type/'
    | '/caroptions/edit/$id'
    | '/cars/edit/$id'
    | '/carspecs/edit/$id'
    | '/manufacture/edit/$id'
    | '/model/edit/$id'
    | '/transmission/edit/$id'
    | '/type/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  CaroptionsIdLazyRoute: typeof CaroptionsIdLazyRoute
  CaroptionsCreateLazyRoute: typeof CaroptionsCreateLazyRoute
  CarsIdLazyRoute: typeof CarsIdLazyRoute
  CarsCreateLazyRoute: typeof CarsCreateLazyRoute
  CarspecsIdLazyRoute: typeof CarspecsIdLazyRoute
  CarspecsCreateLazyRoute: typeof CarspecsCreateLazyRoute
  ManufactureIdLazyRoute: typeof ManufactureIdLazyRoute
  ManufactureCreateLazyRoute: typeof ManufactureCreateLazyRoute
  ModelIdLazyRoute: typeof ModelIdLazyRoute
  ModelCreateLazyRoute: typeof ModelCreateLazyRoute
  TransmissionIdLazyRoute: typeof TransmissionIdLazyRoute
  TransmissionCreateLazyRoute: typeof TransmissionCreateLazyRoute
  TypeIdLazyRoute: typeof TypeIdLazyRoute
  TypeCreateLazyRoute: typeof TypeCreateLazyRoute
  CaroptionsIndexLazyRoute: typeof CaroptionsIndexLazyRoute
  CarsIndexLazyRoute: typeof CarsIndexLazyRoute
  CarspecsIndexLazyRoute: typeof CarspecsIndexLazyRoute
  ManufactureIndexLazyRoute: typeof ManufactureIndexLazyRoute
  ModelIndexLazyRoute: typeof ModelIndexLazyRoute
  TransmissionIndexLazyRoute: typeof TransmissionIndexLazyRoute
  TypeIndexLazyRoute: typeof TypeIndexLazyRoute
  CaroptionsEditIdLazyRoute: typeof CaroptionsEditIdLazyRoute
  CarsEditIdLazyRoute: typeof CarsEditIdLazyRoute
  CarspecsEditIdLazyRoute: typeof CarspecsEditIdLazyRoute
  ManufactureEditIdLazyRoute: typeof ManufactureEditIdLazyRoute
  ModelEditIdLazyRoute: typeof ModelEditIdLazyRoute
  TransmissionEditIdLazyRoute: typeof TransmissionEditIdLazyRoute
  TypeEditIdLazyRoute: typeof TypeEditIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  CaroptionsIdLazyRoute: CaroptionsIdLazyRoute,
  CaroptionsCreateLazyRoute: CaroptionsCreateLazyRoute,
  CarsIdLazyRoute: CarsIdLazyRoute,
  CarsCreateLazyRoute: CarsCreateLazyRoute,
  CarspecsIdLazyRoute: CarspecsIdLazyRoute,
  CarspecsCreateLazyRoute: CarspecsCreateLazyRoute,
  ManufactureIdLazyRoute: ManufactureIdLazyRoute,
  ManufactureCreateLazyRoute: ManufactureCreateLazyRoute,
  ModelIdLazyRoute: ModelIdLazyRoute,
  ModelCreateLazyRoute: ModelCreateLazyRoute,
  TransmissionIdLazyRoute: TransmissionIdLazyRoute,
  TransmissionCreateLazyRoute: TransmissionCreateLazyRoute,
  TypeIdLazyRoute: TypeIdLazyRoute,
  TypeCreateLazyRoute: TypeCreateLazyRoute,
  CaroptionsIndexLazyRoute: CaroptionsIndexLazyRoute,
  CarsIndexLazyRoute: CarsIndexLazyRoute,
  CarspecsIndexLazyRoute: CarspecsIndexLazyRoute,
  ManufactureIndexLazyRoute: ManufactureIndexLazyRoute,
  ModelIndexLazyRoute: ModelIndexLazyRoute,
  TransmissionIndexLazyRoute: TransmissionIndexLazyRoute,
  TypeIndexLazyRoute: TypeIndexLazyRoute,
  CaroptionsEditIdLazyRoute: CaroptionsEditIdLazyRoute,
  CarsEditIdLazyRoute: CarsEditIdLazyRoute,
  CarspecsEditIdLazyRoute: CarspecsEditIdLazyRoute,
  ManufactureEditIdLazyRoute: ManufactureEditIdLazyRoute,
  ModelEditIdLazyRoute: ModelEditIdLazyRoute,
  TransmissionEditIdLazyRoute: TransmissionEditIdLazyRoute,
  TypeEditIdLazyRoute: TypeEditIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/login",
        "/profile",
        "/register",
        "/caroptions/$id",
        "/caroptions/create",
        "/cars/$id",
        "/cars/create",
        "/carspecs/$id",
        "/carspecs/create",
        "/manufacture/$id",
        "/manufacture/create",
        "/model/$id",
        "/model/create",
        "/transmission/$id",
        "/transmission/create",
        "/type/$id",
        "/type/create",
        "/caroptions/",
        "/cars/",
        "/carspecs/",
        "/manufacture/",
        "/model/",
        "/transmission/",
        "/type/",
        "/caroptions/edit/$id",
        "/cars/edit/$id",
        "/carspecs/edit/$id",
        "/manufacture/edit/$id",
        "/model/edit/$id",
        "/transmission/edit/$id",
        "/type/edit/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/login": {
      "filePath": "login.lazy.jsx"
    },
    "/profile": {
      "filePath": "profile.lazy.jsx"
    },
    "/register": {
      "filePath": "register.lazy.jsx"
    },
    "/caroptions/$id": {
      "filePath": "caroptions/$id.lazy.jsx"
    },
    "/caroptions/create": {
      "filePath": "caroptions/create.lazy.jsx"
    },
    "/cars/$id": {
      "filePath": "cars/$id.lazy.jsx"
    },
    "/cars/create": {
      "filePath": "cars/create.lazy.jsx"
    },
    "/carspecs/$id": {
      "filePath": "carspecs/$id.lazy.jsx"
    },
    "/carspecs/create": {
      "filePath": "carspecs/create.lazy.jsx"
    },
    "/manufacture/$id": {
      "filePath": "manufacture/$id.lazy.jsx"
    },
    "/manufacture/create": {
      "filePath": "manufacture/create.lazy.jsx"
    },
    "/model/$id": {
      "filePath": "model/$id.lazy.jsx"
    },
    "/model/create": {
      "filePath": "model/create.lazy.jsx"
    },
    "/transmission/$id": {
      "filePath": "transmission/$id.lazy.jsx"
    },
    "/transmission/create": {
      "filePath": "transmission/create.lazy.jsx"
    },
    "/type/$id": {
      "filePath": "type/$id.lazy.jsx"
    },
    "/type/create": {
      "filePath": "type/create.lazy.jsx"
    },
    "/caroptions/": {
      "filePath": "caroptions/index.lazy.jsx"
    },
    "/cars/": {
      "filePath": "cars/index.lazy.jsx"
    },
    "/carspecs/": {
      "filePath": "carspecs/index.lazy.jsx"
    },
    "/manufacture/": {
      "filePath": "manufacture/index.lazy.jsx"
    },
    "/model/": {
      "filePath": "model/index.lazy.jsx"
    },
    "/transmission/": {
      "filePath": "transmission/index.lazy.jsx"
    },
    "/type/": {
      "filePath": "type/index.lazy.jsx"
    },
    "/caroptions/edit/$id": {
      "filePath": "caroptions/edit/$id.lazy.jsx"
    },
    "/cars/edit/$id": {
      "filePath": "cars/edit/$id.lazy.jsx"
    },
    "/carspecs/edit/$id": {
      "filePath": "carspecs/edit/$id.lazy.jsx"
    },
    "/manufacture/edit/$id": {
      "filePath": "manufacture/edit/$id.lazy.jsx"
    },
    "/model/edit/$id": {
      "filePath": "model/edit/$id.lazy.jsx"
    },
    "/transmission/edit/$id": {
      "filePath": "transmission/edit/$id.lazy.jsx"
    },
    "/type/edit/$id": {
      "filePath": "type/edit/$id.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
